# More information about the configuration file can be found here:
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-config.html
version = 0.1

[default]
[default.global.parameters]
stack_name = "sam-app"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
resolve_s3 = false
s3_prefix = "sam-app-pipeline"
region = "us-east-1"
image_repositories = []
stack_name = "sam-app-pipeline"
parameter_overrides = "GitProviderType=\"CodeCommit\" CodeCommitRepositoryName=\"sam-app\" MainGitBranch=\"main\" SamTemplate=\"template.yaml\" TestingRegion=\"us-east-1\" TestingStackName=\"sam-app\" TestingPipelineExecutionRole=\"arn:aws:iam::706652976335:role/aws-sam-cli-managed-dev-pipe-PipelineExecutionRole-1NY7CKWQ50PTQ\" TestingCloudFormationExecutionRole=\"arn:aws:iam::706652976335:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionR-1P09VP67MW4YL\" TestingArtifactBucket=\"amacp\" TestingImageRepository=\"\" ProdRegion=\"us-east-1\" ProdStackName=\"sam-app\" ProdPipelineExecutionRole=\"arn:aws:iam::706652976335:role/aws-sam-cli-managed-prod-pip-PipelineExecutionRole-37U92TU7TD0K\" ProdCloudFormationExecutionExeRole=\"arn:aws:iam::706652976335:role/aws-sam-cli-managed-prod-CloudFormationExecutionR-1EW38HTI4B9EQ\" ProdArtifactBucket=\"amacp\" ProdImageRepository=\"\" CodeStarConnectionArn=\"\" FeatureGitBranch=\"\""
disable_rollback = true

[default.package.parameters]
resolve_s3 = true

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
